# Generated by Django 3.2 on 2023-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_alter_bookinfo_bpub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
