# Generated by Django 3.2 on 2023-03-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_alter_bookinfo_btitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
