# Generated by Django 3.2 on 2023-03-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_alter_bookinfo_bread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='booktest.bookinfo'),
        ),
    ]
