# Generated by Django 3.2 on 2023-03-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0010_areas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
